In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/content/player_match_history.csv")

In [3]:
df.head()

,element,fixture,opponent_team,total_points,was_home,kickoff_time,team_h_score,team_a_score,round,modified,...,expected_goals,expected_assists,expected_goal_involvements,expected_goals_conceded,value,transfers_balance,selected,transfers_in,transfers_out,player_id
0,1,9,14,10,False,2025-08-17T15:30:00Z,0.0,1.0,1,False,...,0.0,0.00,0.00,1.52,55,0,1531911,0,0,1
1,1,11,11,6,True,2025-08-23T16:30:00Z,5.0,0.0,2,False,...,0.0,0.00,0.00,0.17,55,218659,2284634,277339,58680,1
2,1,25,12,2,False,2025-08-31T15:30:00Z,1.0,0.0,3,False,...,0.0,0.02,0.02,0.52,55,-12311,2406964,146739,159050,1
3,1,31,16,6,True,2025-09-13T11:30:00Z,3.0,0.0,4,False,...,0.0,0.00,0.00,0.20,55,171289,2765759,289041,117752,1
4,1,41,13,2,True,2025-09-21T15:30:00Z,1.0,1.0,5,False,...,0.0,0.01,0.01,0.89,55,-9786,2762632,98100,107886,1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22343 entries, 0 to 22342
Data columns (total 42 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   element                          22343 non-null  int64
 1   fixture                          22343 non-null  int64
 2   opponent_team                    22343 non-null  int64
 3   total_points                     22343 non-null  int64
 4   was_home                         22343 non-null  bool
 5   kickoff_time                     22343 non-null  object
 6   team_h_score                     21857 non-null  float64
 7   team_a_score                     21857 non-null  float64
 8   round                            22343 non-null  int64
 9   modified                         22343 non-null  bool
 10  minutes                          22343 non-null  int64
 11  goals_scored                     22343 non-null  int64
 12  assists                          22343 non-null  int64
 13  clean_sheets                     22343 non-null  int64
 14  goals_conceded                   22343 non-null  int64
 15  own_goals                        22343 non-null  int64
 16  penalties_saved                  22343 non-null  int64
 17  penalties_missed                 22343 non-null  int64
 18  yellow_cards                     22343 non-null  int64
 19  red_cards                        22343 non-null  int64
 20  saves                            22343 non-null  int64
 21  bonus                            22343 non-null  int64
 22  bps                              22343 non-null  int64
 23  influence                        22343 non-null  float64
 24  creativity                       22343 non-null  float64
 25  threat                           22343 non-null  float64
 26  ict_index                        22343 non-null  float64
 27  clearances_blocks_interceptions  22343 non-null  int64
 28  recoveries                       22343 non-null  int64
 29  tackles                          22343 non-null  int64
 30  defensive_contribution           22343 non-null  int64
 31  starts                           22343 non-null  int64
 32  expected_goals                   22343 non-null  float64
 33  expected_assists                 22343 non-null  float64
 34  expected_goal_involvements       22343 non-null  float64
 35  expected_goals_conceded          22343 non-null  float64
 36  value                            22343 non-null  int64
 37  transfers_balance                22343 non-null  int64
 38  selected                         22343 non-null  int64
 39  transfers_in                     22343 non-null  int64
 40  transfers_out                    22343 non-null  int64
 41  player_id                        22343 non-null  int64
dtypes: bool(2), float64(10), int64(29), object(1)
memory usage: 6.9+ MB

In [ ]:
df.describe()

,element,fixture,opponent_team,total_points,team_h_score,team_a_score,round,minutes,goals_scored,assists,...,expected_goals,expected_assists,expected_goal_involvements,expected_goals_conceded,value,transfers_balance,selected,transfers_in,transfers_out,player_id
count,22343.000000,22343.000000,22343.000000,22343.000000,21857.000000,21857.000000,22343.000000,22343.000000,22343.000000,22343.000000,...,22343.000000,22343.000000,22343.000000,22343.000000,22343.000000,2.234300e+04,2.234300e+04,2.234300e+04,2.234300e+04,22343.000000
mean,385.336795,149.817392,10.478897,1.156201,1.521938,1.235302,15.413642,25.126751,0.033836,0.031822,...,0.035503,0.022285,0.057781,0.386173,49.521148,9.619756e+01,2.418344e+05,1.612912e+04,1.603293e+04,385.336795
std,223.471907,84.024215,5.784711,2.358680,1.167398,1.086294,8.366662,37.305351,0.198511,0.185208,...,0.132351,0.073497,0.166110,0.687998,10.885694,8.827847e+04,7.216694e+05,7.272119e+04,6.630648e+04,223.471907
min,1.000000,1.000000,1.000000,-3.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,37.000000,-2.993262e+06,0.000000e+00,0.000000e+00,0.000000e+00,1.000000
25%,192.000000,78.000000,5.000000,0.000000,1.000000,0.000000,8.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,43.000000,-1.233500e+03,6.061000e+03,1.900000e+01,1.350000e+02,192.000000
50%,385.000000,152.000000,10.000000,0.000000,1.000000,1.000000,16.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,47.000000,-9.900000e+01,2.154600e+04,3.390000e+02,8.610000e+02,385.000000
75%,577.000000,223.000000,15.000000,1.000000,2.000000,2.000000,23.000000,65.000000,0.000000,0.000000,...,0.000000,0.010000,0.020000,0.550000,54.000000,1.200000e+01,1.099745e+05,3.235500e+03,5.977000e+03,577.000000
max,820.000000,310.000000,20.000000,24.000000,5.000000,5.000000,29.000000,90.000000,3.000000,2.000000,...,3.670000,1.110000,3.700000,4.440000,151.000000,1.634966e+06,9.515178e+06,1.670976e+06,3.024167e+06,820.000000

In [ ]:
df['element']

0          1
1          1
2          1
3          1
4          1
        ...
22338    817
22339    817
22340    817
22341    817
22342    817
Name: element, Length: 22343, dtype: int64

In [ ]:
df.columns

Index(['element', 'fixture', 'opponent_team', 'total_points', 'was_home',
       'kickoff_time', 'team_h_score', 'team_a_score', 'round', 'modified',
       'minutes', 'goals_scored', 'assists', 'clean_sheets', 'goals_conceded',
       'own_goals', 'penalties_saved', 'penalties_missed', 'yellow_cards',
       'red_cards', 'saves', 'bonus', 'bps', 'influence', 'creativity',
       'threat', 'ict_index', 'clearances_blocks_interceptions', 'recoveries',
       'tackles', 'defensive_contribution', 'starts', 'expected_goals',
       'expected_assists', 'expected_goal_involvements',
       'expected_goals_conceded', 'value', 'transfers_balance', 'selected',
       'transfers_in', 'transfers_out', 'player_id'],
      dtype='object')

In [5]:
df = df['element', 'fixture', 'opponent_team',
        #'total_points',
         'was_home','kickoff_time',
        #'team_h_score', 'team_a_score',
        'round', 'modified','minutes', 'goals_scored', 'assists', 'clean_sheets', 'goals_conceded',
       'own_goals', 'penalties_saved', 'penalties_missed', 'yellow_cards',
       'red_cards', 'saves', 'bonus', 'bps', 'influence', 'creativity',
       'threat', 'ict_index', 'clearances_blocks_interceptions', 'recoveries',
       'tackles', 'defensive_contribution', 'starts', 'expected_goals',
       'expected_assists', 'expected_goal_involvements',
       'expected_goals_conceded', 'value', 'transfers_balance', 'selected',
       'transfers_in', 'transfers_out', 'player_id']

KeyError: ('element', 'fixture', 'opponent_team', 'was_home', 'kickoff_time', 'round', 'modified', 'minutes', 'goals_scored', 'assists', 'clean_sheets', 'goals_conceded', 'own_goals', 'penalties_saved', 'penalties_missed', 'yellow_cards', 'red_cards', 'saves', 'bonus', 'bps', 'influence', 'creativity', 'threat', 'ict_index', 'clearances_blocks_interceptions', 'recoveries', 'tackles', 'defensive_contribution', 'starts', 'expected_goals', 'expected_assists', 'expected_goal_involvements', 'expected_goals_conceded', 'value', 'transfers_balance', 'selected', 'transfers_in', 'transfers_out', 'player_id')

In [6]:
df = df[
[
'opponent_team',
'was_home',
'round',
'minutes',
'starts',
'goals_scored',
'assists',
'clean_sheets',
'goals_conceded',
'saves',
'yellow_cards',
'red_cards',
'influence',
'creativity',
'threat',
'ict_index',
'expected_goals',
'expected_assists',
'expected_goal_involvements',
'expected_goals_conceded',
'tackles',
'clearances_blocks_interceptions',
'recoveries',
'defensive_contribution',
'total_points',
'player_id'
]
].copy()

In [ ]:
df.describe()

,opponent_team,round,minutes,starts,goals_scored,assists,clean_sheets,goals_conceded,saves,yellow_cards,...,expected_goals,expected_assists,expected_goal_involvements,expected_goals_conceded,tackles,clearances_blocks_interceptions,recoveries,defensive_contribution,total_points,player_id
count,22343.000000,22343.000000,22343.000000,22343.000000,22343.000000,22343.000000,22343.00000,22343.000000,22343.000000,22343.000000,...,22343.000000,22343.000000,22343.000000,22343.000000,22343.000000,22343.000000,22343.000000,22343.000000,22343.000000,22343.000000
mean,10.478897,15.413642,25.126751,0.280625,0.033836,0.031822,0.07631,0.388444,0.069641,0.047397,...,0.035503,0.022285,0.057781,0.386173,0.429531,0.998568,1.201405,1.988050,1.156201,385.336795
std,5.784711,8.366662,37.305351,0.449315,0.198511,0.185208,0.26550,0.820189,0.512822,0.212492,...,0.132351,0.073497,0.166110,0.687998,1.011499,2.277715,2.273464,3.677016,2.358680,223.471907
min,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-3.000000,1.000000
25%,5.000000,8.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,192.000000
50%,10.000000,16.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,385.000000
75%,15.000000,23.000000,65.000000,1.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.010000,0.020000,0.550000,0.000000,1.000000,2.000000,3.000000,1.000000,577.000000
max,20.000000,29.000000,90.000000,1.000000,3.000000,2.000000,1.00000,5.000000,10.000000,1.000000,...,3.670000,1.110000,3.700000,4.440000,11.000000,22.000000,18.000000,29.000000,24.000000,820.000000

In [ ]:
df.shape

(22343, 26)

In [ ]:
df = df.sort_values(["player_id", "round"])

In [ ]:
df.head()

,opponent_team,was_home,round,minutes,starts,goals_scored,assists,clean_sheets,goals_conceded,saves,...,expected_goals,expected_assists,expected_goal_involvements,expected_goals_conceded,tackles,clearances_blocks_interceptions,recoveries,defensive_contribution,total_points,player_id
0,14,False,1,90,1,0,0,1,0,7,...,0.0,0.00,0.00,1.52,0,1,13,0,10,1
1,11,True,2,90,1,0,0,1,0,1,...,0.0,0.00,0.00,0.17,0,0,3,0,6,1
2,12,False,3,90,1,0,0,0,1,2,...,0.0,0.02,0.02,0.52,0,0,12,0,2,1
3,16,True,4,90,1,0,0,1,0,1,...,0.0,0.00,0.00,0.20,0,0,9,0,6,1
4,13,True,5,90,1,0,0,0,1,2,...,0.0,0.01,0.01,0.89,0,1,6,0,2,1

##Average points from last 3

In [7]:
df["avg_points_last3"] = (
    df.groupby("player_id")["total_points"]
    .shift(1)
    .rolling(3)
    .mean()
)

In [8]:
df["avg_minutes_last3"] = (
    df.groupby("player_id")["minutes"]
    .shift(1)
    .rolling(3)
    .mean()
)

In [9]:
df["xG_last5"] = (
    df.groupby("player_id")["expected_goals"]
    .shift(1)
    .rolling(5)
    .mean()
)

In [10]:
df["xA_last5"] = (
    df.groupby("player_id")["expected_assists"]
    .shift(1)
    .rolling(5)
    .mean()
)

In [11]:
df = df.dropna()

In [12]:
print(df[[
"player_id",
"round",
"total_points",
"avg_points_last3",
"avg_minutes_last3",
"xG_last5",
"xA_last5"
]].head(15))

    player_id  round  total_points  avg_points_last3  avg_minutes_last3  \
5           1      6             2          3.333333               90.0
6           1      7             6          3.333333               90.0
7           1      8             6          3.333333               90.0
8           1      9             6          4.666667               90.0
9           1     10             6          6.000000               90.0
10          1     11             1          6.000000               90.0
11          1     12             2          4.333333               90.0
12          1     13             3          3.000000               90.0
13          1     14             6          2.000000               90.0
14          1     15             2          3.666667               90.0
15          1     16             2          3.666667               90.0
16          1     17             7          3.333333               90.0
17          1     18             2          3.666667               90.0
18          1     19             2          3.666667               90.0
19          1     20             1          3.666667               90.0

    xG_last5  xA_last5
5        0.0     0.006
6        0.0     0.008
7        0.0     0.008
8        0.0     0.004
9        0.0     0.004
10       0.0     0.002
11       0.0     0.000
12       0.0     0.000
13       0.0     0.000
14       0.0     0.000
15       0.0     0.000
16       0.0     0.000
17       0.0     0.000
18       0.0     0.000
19       0.0     0.000

In [13]:
df = df.dropna().reset_index(drop=True)

In [14]:
df["xGI_last5"] = (
    df.groupby("player_id")["expected_goal_involvements"]
    .shift(1)
    .rolling(5)
    .mean()
)

In [16]:
df.to_csv("fpl_training_dataset.csv",index = False)
print("Dataset exported successfully")
print("Shape:", df.shape)

Dataset exported successfully
Shape: (18252, 31)

In [19]:
from google.colab import files

In [20]:
files.download("fpl_training_dataset.csv")

In [21]:
df.head()

,opponent_team,was_home,round,minutes,starts,goals_scored,assists,clean_sheets,goals_conceded,saves,...,clearances_blocks_interceptions,recoveries,defensive_contribution,total_points,player_id,avg_points_last3,avg_minutes_last3,xG_last5,xA_last5,xGI_last5
0,15,False,6,90,1,0,0,0,1,2,...,2,10,0,2,1,3.333333,90.0,0.0,0.006,NaN
1,19,True,7,90,1,0,0,1,0,0,...,0,8,0,6,1,3.333333,90.0,0.0,0.008,NaN
2,10,False,8,90,1,0,0,1,0,0,...,2,7,0,6,1,3.333333,90.0,0.0,0.008,NaN
3,8,True,9,90,1,0,0,1,0,1,...,2,10,0,6,1,4.666667,90.0,0.0,0.004,NaN
4,3,False,10,90,1,0,0,1,0,0,...,1,7,0,6,1,6.000000,90.0,0.0,0.004,NaN